config/routes.rb
Rails.application.routes.draw do
  resources :hightlights
  devise_for :users
  resources :users
  resources :photomoments
  root "static_pages#home"
  get "static_pages/home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hightlight.rb
class Hightlight < ApplicationRecord
  mount_uploader :video, VideoUploader
end

app/models/photomoment.rb
class Photomoment < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  enum gender: [:Male, :Female, :Both]
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :gender, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :gender, :avatar, :name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/hightlights_controller.rb
class HightlightsController < ApplicationController
  before_action :set_hightlight, only: [:edit, :update, :destroy]

  def index
    @q = Hightlight.ransack(params[:q])
    @hightlights = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10).order('created_at desc')
  end

  def new
    @hightlight = Hightlight.new
  end

  def edit
  end

  def create
    @hightlight = Hightlight.new(hightlight_params)
    respond_to do |format|
      if @hightlight.save
        format.html { redirect_to hightlights_url, notice: 'Hightlight was successfully created.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :new }
        format.json { render json: @hightlight.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hightlight.update(hightlight_params)
        format.html { redirect_to hightlights_url, notice: 'Hightlight was successfully updated.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @hightlight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hightlight.destroy
    respond_to do |format|
      format.html { redirect_to hightlights_url, notice: 'Hightlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_hightlight
      @hightlight = Hightlight.find(params[:id])
    end

    def hightlight_params
      params.require(:hightlight).permit(:name, :video)
    end
end

app/controllers/photomoments_controller.rb
class PhotomomentsController < ApplicationController
  def new
    @photomoment = Photomoment.new
  end

  def create
    @photomoment = Photomoment.new(photomoment_params)
    if @photomoment.save
      flash[:success] = "Create photomoment success!"
      redirect_to photomoments_path
    else
      flash[:danger] = "The data entry is missing!"
      render :new
    end
  end

  def edit
    @photomoment = Photomoment.find(params[:id])
  end

  def update
    @photomoment = Photomoment.find(params[:id])
    if @photomoment.update(photomoment_params)
      flash[:success] = "Profile updated"
      redirect_to photomoments_path
    else
      render 'edit'
    end
  end
  def index
    @q = Photomoment.ransack(params[:q])
    @photomoments = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10).order('created_at desc')
  end

  private

  def photomoment_params
    params.require(:photomoment).permit(:name, :image)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hightlights_helper.rb
module HightlightsHelper
end

app/views/hightlights/_form.html.erb
<%= form_with(model: hightlight, local: true) do |f| %>
  <% if hightlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hightlight.errors.count, "error") %> prohibited this hightlight from being saved:</h2>
      <ul>
        <% hightlight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :video %>
    <%= f.file_field :video %><br>
    <%= f.submit "Thêm Video", class: "btn btn-primary" %>
  <div class="actions">
  </div>
<% end %>

app/views/hightlights/edit.html.erb
<h1>Editing Hightlight</h1>

<%= render 'form', hightlight: @hightlight %>

<%= link_to 'Show', @hightlight %> |
<%= link_to 'Back', hightlights_path %>

app/views/hightlights/index.html.erb
<% provide :title, "Hightlight" %>
<div class="home">
  <%= render "static_pages/header" %>
  <div class="row">
    <div class="col-sm-7">
        <h2>Hightlight of NSB</h2>
    </div>
    <div class="col-sm-5">
      <%= search_form_for @q, url: hightlights_path, method: :get do |f| %>
        <%= f.text_field :name_cont, placeholder: "Tiêu đề", id: "input-player" %>
        <%= button_tag( :class => "button_green") do %>
          <i class="fa fa-search" aria-hidden="true"></i></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <% @hightlights.each do |hightlight| %>
    <div class="polaroid">
      <%= video_tag hightlight.video_url.to_s, controls: true %>
      <div class="name-photo">
      <%= hightlight.name %>
      </div>
    </div>
    <% end %>
  <p><%= will_paginate @hightlights %></p>
</div>

app/views/hightlights/new.html.erb
<% provide :title, "Thêm Video" %>
<div class="home">
<%= render "static_pages/header" %>
<%= render 'form', hightlight: @hightlight %>
</div>

app/views/layouts/_tab_left.html.erb
<div class="logo">
  <img src="https://s2.ephoto360.com/images/user_image/2020/08/5f3b3d2aafb4b.jpg" alt="NSBTerritory" width="321" height="900">
</div>

app/views/layouts/_tab_right.html.erb
<div class="logo">
  <img src="https://s2.ephoto360.com/images/user_image/2020/08/5f3b3d9d68f2b.jpg" alt="NSBTerritory" width="321" height="900">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | NSB_Territory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  </head>

  <body>
    <div class="row">
  <div class="col-sm-3" style="padding-left: 0px;
    padding-right: 0px;">
    <%= render "layouts/tab_left" %>
  </div>
  <div class="col-sm-6" style="padding-left: 0px;
    padding-right: 0px;">
    <%= yield %>
  </div>
  <div class="col-sm-3" style="padding-left: 0px;
    padding-right: 0px;">
    <%= render "layouts/tab_right" %>
  </div>
    </div>
      <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  </body>
</html>

app/views/photomoments/edit.html.erb
<% provide :title, "Thêm Ảnh" %>
<div class="home">
<%= render "static_pages/header" %>
<h2>Thêm Ảnh</h2>
<%= form_for :photomoment, url: {action: :update, controller: :photomoments}, method: :put do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :image %>
    <%= f.file_field :image %><br>
    <%= f.submit "Thêm Ảnh", class: "btn btn-primary" %>
<% end %>
</div>

app/views/photomoments/index.html.erb
<% provide :title, "Photomoment" %>
<div class="home">
  <%= render "static_pages/header" %>
  <div class="row">
    <div class="col-sm-7">
        <h2>Photo Moments Of NSB</h2>
    </div>
    <div class="col-sm-5">
      <%= search_form_for @q, url: photomoments_path, method: :get do |f| %>
        <%= f.text_field :name_cont, placeholder: "Tiêu đề", id: "input-player" %>
        <%= button_tag( :class => "button_green") do %>
          <i class="fa fa-search" aria-hidden="true"></i></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <% @photomoments.each do |photomoment| %>
    <div class="polaroid">
      <%= image_tag(photomoment.image.url) %>
      <div class="name-photo">
        <%= photomoment.name %>
      </div>
    </div>
  <% end %>
  <p><%= will_paginate @photomoments %></p>
</div>

app/views/photomoments/new.html.erb
<% provide :title, "Thêm Ảnh" %>
<div class="home">
<%= render "static_pages/header" %>
<h2>Thêm Ảnh</h2>
<%= form_for :photomoment, url: {action: :create, controller: :photomoments}, method: :post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :image %>
    <%= f.file_field :image %><br>
    <%= f.submit "Thêm Ảnh", class: "btn btn-primary" %>
<% end %>
</div>

app/views/static_pages/_header.html.erb
<div class="header">
  <%= link_to root_path do %>
     <%= image_tag "http://r52.cooltext.com/d.php?renderid=360192585945242&extension=png" %>
  <% end %>
  <div id="menu">
    <ul>
      <li><%= link_to "Trang chủ", root_path %></li>
      <li><%= link_to "Hình Ảnh", photomoments_path %>
      <li><%= link_to "Hightlight", hightlights_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Tài Khoản", user_path(current_user) %></li>
        <li><%= link_to "Đăng Xuất", destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to "Đăng Kí", new_user_registration_path %></li>
        <li><%= link_to "Đăng Nhập", user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide :title, "Trang Chủ" %>
<div class="home">
  <%= render "static_pages/header" %>
</div>

app/views/users/show.html.erb
<% provide :title, "Tài Khoản" %>
<div class="home">
<%= render "static_pages/header" %>
<h2>Thông tin tài khoản</h2>
<div class="show-user">
  <% if @user.avatar.present? %>
    <%= image_tag(@user.avatar.url) %>
  <% else %>
    <img src="https://png.pngtree.com/png-vector/20191110/ourlarge/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg" height="235" width="235">
    <%= link_to "Edit", edit_user_registration_path , class: "btn btn-primary" %>
  <% end %>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <h5><i class="fa fa-envelope-o" aria-hidden="true"></i>&nbspEmail: <%= @user.email %></h5>
      <h5><i class="fa fa-transgender-alt" aria-hidden="true"></i>&nbspGender: <%= @user.gender %></h5>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <h5><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbspName: <%= @user.name %></h5>
    </div>
  </div>
</div>
</div>